import { Inter } from "next/font/google";
import "./globals.css";
import Header from "./header";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className="h-full min-h-screen max-h-screen  w-full min-w-[100vw] max-w-[100vw] overflow-hidden"
    >
      <body
        className={`h-full min-h-screen max-h-screen w-full min-w-[100vw] max-w-[100vw] overflow-auto`}
      >
        <Header />
        {children}
      </body>
    </html>
  );
}
